function obj = linearRegressionScoreFcns(llstr)
    if strcmp(llstr, 'poiss')
        obj.llFcn0 = @(x, y, w, hyper) -tools.neglogli_poissGLM(w, ...
            tools.ifNecessaryAddDC(x, w), y, @tools.expfun);
        obj.llSatFcn = @(trials) -tools.neglogli_poissGLM(1, ...
            trials.y_test, trials.y_test, @(x) x);
    elseif strcmp(llstr, 'gauss')
        obj.llFcn0 = @(x, y, w, hyper) asd.gauss.logLikelihood(y, ...
            tools.ifNecessaryAddDC(x, w), w, hyper(2));
    end
    obj.llFcn = @(trials, w, hyper) obj.llFcn0(trials.x_test, ...
        trials.y_test, w, hyper);
    obj.llNullFcn = @(trials, hyper) obj.llFcn0(...
        mean(trials.y_train)*ones(size(trials.y_test,1),1), ...
        trials.y_test, 1, hyper);
    
    obj.rsqFcn = @(trials, w, hyper) ...
        tools.rsq(tools.ifNecessaryAddDC(trials.x_test, w)*w, trials.y_test);
    
    rssFcn = @(y, yh) (y-yh)'*(y-yh);
    obj.rssFcn = @(trials, w, hyper) ...
        rssFcn(tools.ifNecessaryAddDC(trials.x_test, w)*w, trials.y_test);
    obj.tssFcn = @(trials, w, hyper) rssFcn(...
        mean(trials.y_train)*ones(size(trials.y_test,1),1), ...
        trials.y_test);
    
    obj.pseudoRsqFcn = @(trials, w, hyper) ...
        tools.pseudoRsq(...
            obj.llFcn(trials, w, hyper), ... % actual model            
            obj.llSatFcn(trials), ... % saturated model
            obj.llNullFcn(trials, hyper)); % null model
end
