function obj = logisticRegressionScoreFcns()
    obj.llFcn0 = @(x, y, w, hyper) ...
        -tools.neglogli_bernoulliGLM(w, tools.ifNecessaryAddDC(x, w), y);
    obj.llFcn = @(trials, w, hyper) ...
        obj.llFcn0(trials.x_test, trials.y_test, w, hyper);
    
    obj.rsqFcn = @(trials, w, hyper) ...
        tools.rsq(tools.logistic(...
            tools.ifNecessaryAddDC(trials.x_test,w)*w), trials.y_test);

    obj.pseudoRsqFcn = @(trials, w, hyper) ...
        tools.pseudoRsq(...
            obj.llFcn(trials, w, hyper), ... % actual model
            0, ... % saturated model
            obj.llFcn0(... % null model
                mean(trials.y_train)*ones(size(trials.y_test,1),1), ...
                    trials.y_test, 1, hyper));
%             M.llFcn0(trials.y_test, trials.y_test, 1, hyper), ...  % saturated model
end
